### ISSUE TITLE
Remove max response size 

### ISSUE THREAD

**Issue by pixelchef** [contentful/contentful-export#32]
I'm trying to export a backup of my content library and hitting the limit. ```"Response size too big, was: 15951862b. Maximum allowed response size: 7340032b.```

**Comment by pixelchef** [comment]
Perhaps adding a way the exporter will automatically break up large requests like this would be helpful

**Comment by Khaledgarbaya** [comment]
hi @pixelchef ,
The problem is that the default number of records per page is 1000. You can control that by specifying `--max-allowed-limit`, which is [here](https://github.com/contentful/contentful-export/blob/master/lib/usageParams.js#L41),  so the response will be smaller. I think setting it to `100` will be more than enough for your case.

Best,
Khaled
