### ISSUE TITLE
--include-drafts should actually be --drafts-only?

### ISSUE THREAD

**Issue by steve-a-jones** [contentful/contentful-export#40]
A few thoughts regarding the `--include-drafts` flag:

- I'm aware that draft exports aren't supported (as stated under limitations "Draft entries are not supported.") - should this argument be parsed at all in the current version if that is the case?

- Passing `--include-drafts` actually _filters_ all entries for type draft - should this flag be renamed to --drafts-only or perhaps instead introduce an entry type filter argument for filtering entries by type (draft, published, etc..)?

Heres where the filter is being applied : https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-full-source-space.js#L28

Apologies if i'm missing something simple here or if this has already been discussed.

**Comment by axe312ger** [comment]
That was fixed with `v5.3.0` which actually just came out a few hours after u opened the issue. All good, please just upgrade, it will behave as expected afterwards :)

**Comment by iddan** [comment]
Is this fixed in the latest released version on NPM?

**Comment by axe312ger** [comment]
@iddan yes, it is or ... should be. If you still experience this, please try our rewrite/new beta via `npm install -g contentful-export@next`. I'd love to hear if it works for you in that new version :)

**Comment by iddan** [comment]
Oh, I should have included @next... This is a serious bug when are you going to stabilise version 5?

**Comment by axe312ger** [comment]
It is more or less on top of your todo list for the JS tooling. We hope to get it out this year, otherwise early 2018.

**Comment by iddan** [comment]
How dangerous is it to use right now?

**Comment by axe312ger** [comment]
Since export is not touching your space at all, the export beta can be used without any fears.

For the import version, this is not that easy to answer. It has increased test coverage, multiple bugs fixed and turned out to be more reliable in our internal tests. Also, import does not delete any content.
We did not encounter any destroyed/faulty content in our tests after importing, but still, we mark it as beta since we did not fully complete all our tests and bugfixes, yet. Use it at your own risk.

Both versions also provide proper error logging now which will help you a lot when debugging failed exports/imports.

Most import problems are related to faulty content in the first place and not really related to the tool itself.

If you are importing into a production space, I'd recommend to test it first on a non-production space, see if everything is fine and then run on production after a successful run. Just to be sure.

Hope that helps,
Benedikt
