### ISSUE TITLE
Support for incremental backup

### ISSUE THREAD

**Issue by moimael** [contentful/contentful-export#57]
HI,

It would be awesome if this tool supported incremental backup, so we can run regular backup without exploding bandwidth and storage usage.

Thanks !

**Comment by axe312ger** [comment]
Hey Moimael,

can you be more exact here, what would you like to backup incremental? Just the content-model or your content/assets? Or all of it?

The simplest solution, that comes to my mind at the moment, would be the following:

Adding an option like `--changed-since` which would lead to an export only containing data which was changed since the given date.

That can be achieved by adding a search parameter like `'sys.updatedAt[gte]': '2013-01-01T00:00:00Z'` to the method call in
https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-full-source-space.js#L146

Would that fit your needs?

All the best,
Benedikt

**Comment by moimael** [comment]
Ideally I'd like to backup everything incrementally :) Proposed solution sound good, will everything be "merged" into the same backup ? Or will this allow to support rollback ? And what about importing it again ?

Thanks !

**Comment by Khaledgarbaya** [comment]
Hi @moimael,
I don't think it will be merged in the previous backup. Mainly export tool is meant to have a copy of your space that represents it at a specific point in time. for incremental backup maybe you can check our [sync](https://www.contentful.com/developers/docs/concepts/sync/) API, but this will allow you get only what changed between two points in time.
the downside of that you will only get the published content.

**Comment by axe312ger** [comment]
We introduced `--query-entries` and `--query-assets` in the latest major version to pass additional query parameters. With that, sth like `'sys.updatedAt[gte]': '2013-01-01T00:00:00Z'` should be possible now.

Closing here, feel free to reopen when this is still an issue.
