### ISSUE TITLE
How many API calls per export/import

### ISSUE THREAD

**Issue by ardalann** [contentful/contentful-export#58]
As Contentful uses the number of API calls in its pricing model, it'd be very useful if it's described on README how we can calculate the number of API calls that will be made per export/import with `contentful-export` and `contentful-import`.

**Comment by Khaledgarbaya** [comment]
Hi @ardalann,
contentful-export does not use much depends on your data.
for contentful-import it is kinda tricky to get an exact number.
for example an entry needs to be created and published so that's 2 per entry, same for contentTypes. for assets 1 request for creation, 1 request for processing and one for publishing (could be more if the asset has more than 1 locale). for the rest it is just creation.
I will try to add something that explains that in the README.
Best,
Khaled

**Comment by ardalann** [comment]
I see. It doesn't have to be exactly accurate, just an estimate would do it.
It'd be great if you can do the same thing for export as well. I know it depends on the data, but maybe something like '1 call per 1000 entries of each type'... 
Thank you! 👍

**Comment by axe312ger** [comment]
Roughly you can say: It is one call per entry plus one for publishing them.

Sorry, can't give you more accurate information since it really depends on the current state of the destination space.
