### ISSUE TITLE
[question] Is there a solution for exporting/backing up asset files?

### ISSUE THREAD

**Issue by jhilden** [contentful/contentful-export#7]
Hi, we are currently archiving a couple of contentful spaces that are no longer used and this tool is coming in real handy. Thanks for that.
However, we also want to archive the asset files from these spaces and as far as I can tell, this tool is only exporting the textual data. Do you also have a prepared solution for downloading all the assets from a space for arachiving purposes?

Thanks

**Comment by Khaledgarbaya** [comment]
Hi @jhilden ,

Unfortunately there is no  plan to do that for now but with a little code I think you can achieve that, since you can use contentful-export [as a library](https://github.com/contentful/contentful-export#usage-as-a-library), you can get the json output and loop through the assets array there and download the assets.

I will be glad to help you and give you some guidance there.

Best,
Khaled

**Comment by jhilden** [comment]
I created a fork and changed your tool so that it works for our asset downloading purpose #10.  It might not yet work for all use/error cases, but maybe it's a base for you to work with.
